from bs4 import BeautifulSoup as bs
import requests as r
import datetime as dt
import calendar
url= "https://www.foxsports.com/college-basketball/abilene-christian-wildcats-team-schedule?season=2019"
amma= r.get(url)
amma_contents = bs(amma.content,"html.parser")
appa=amma_contents.find_all("option")
teams=["""Abilene Christian""","""Air Force""","""Akron""","""Alabama""","""Alabama A&M""","""Alabama State""","""Albany""","""Alcorn State""","""American University""","""Appalachian State""","""Arizona""","""Arizona State""","""Arkansas""","""Arkansas State""","""Arkansas-Little Rock""","""Arkansas-Pine Bluff""","""Army""","""Auburn""","""Austin Peay""","""Ball State""","""Baylor""","""Belmont""","""Bethune-Cookman""","""Binghamton""","""Boise State""","""Boston College""","""Boston University""","""Bowling Green""","""Bradley""","""Brown""","""Bryant University""","""Bucknell""","""Buffalo""","""Butler""","""BYU""","""Cal Poly""","""Cal State Bakersfield""","""Cal State Fullerton""","""Cal State Northridge""","""California""","""California Baptist""","""Campbell""","""Canisius""","""Central Arkansas""","""Central Connecticut State""","""Central Michigan""","""Charleston""","""Charleston Southern""","""Charlotte""","""Chattanooga""","""Chicago State""","""Cincinnati""","""Citadel""","""Clemson""","""Cleveland State""","""Coastal Carolina""","""Colgate""","""Colorado""","""Colorado State""","""Columbia""","""Connecticut""","""Coppin State""","""Cornell""","""Creighton""","""Dartmouth""","""Davidson""","""Dayton""","""Delaware""","""Delaware State""","""Denver""","""DePaul""","""Detroit Mercy""","""Drake""","""Drexel""","""Duke""","""Duquesne""","""East Carolina""","""East Tennessee State""","""Eastern Illinois""","""Eastern Kentucky""","""Eastern Michigan""","""Eastern Washington""","""Elon""","""Evansville""","""Fairfield""","""Fairleigh Dickinson""","""Florida""","""Florida A&M""","""Florida Atlantic""","""Florida Gulf Coast""","""Florida International""","""Florida State""","""Fordham""","""Fresno State""","""Furman""","""Gardner-Webb""","""George Mason""","""George Washington""","""Georgetown""","""Georgia""","""Georgia Southern""","""Georgia State""","""Georgia Tech""","""Gonzaga""","""Grambling State""","""Grand Canyon""","""Green Bay""","""Hampton""","""Hartford""","""Harvard""","""Hawaii""","""High Point""","""Hofstra""","""Holy Cross""","""Houston""","""Houston Baptist""","""Howard""","""Idaho""","""Idaho State""","""Illinois""","""Illinois State""","""Illinois-Chicago""","""Incarnate Word""","""Indiana""","""Indiana State""","""Iona""","""Iowa""","""Iowa State""","""IUPUI""","""Jackson State""","""Jacksonville""","""Jacksonville State""","""James Madison""","""Kansas""","""Kansas City""","""Kansas State""","""Kennesaw State""","""Kent State""","""Kentucky""","""La Salle""","""Lafayette""","""Lamar""","""Lehigh""","""Liberty""","""Lipscomb""","""LIU""","""Long Beach State""","""Longwood""","""Louisiana Tech""","""Louisiana-Lafayette""","""Louisiana-Monroe""","""Louisville""","""Loyola (MD)""","""Loyola Chicago""","""Loyola Marymount""","""LSU""","""Maine""","""Manhattan""","""Marist""","""Marquette""","""Marshall""","""Maryland""","""Maryland-Eastern Shore""","""Massachusetts""","""Massachusetts-Lowell""","""McNeese State""","""Memphis""","""Mercer""","""Merrimack""","""Miami (FL)""","""Miami (OH)""","""Michigan""","""Michigan State""","""Middle Tennessee""","""Milwaukee""","""Minnesota""","""Mississippi State""","""Mississippi Valley State""","""Missouri""","""Missouri State""","""Monmouth""","""Montana""","""Montana State""","""Morehead State""","""Morgan State""","""Mount St. Mary's""","""Murray State""","""N.J.I.T.""","""Navy""","""Nebraska""","""Nebraska-Omaha""","""Nevada""","""New Hampshire""","""New Mexico""","""New Mexico State""","""New Orleans""","""Niagara""","""Nicholls State""","""Norfolk State""","""North Alabama""","""North Carolina""","""North Carolina A&T""","""North Carolina Central""","""North Carolina State""","""North Carolina-Wilmington""","""North Dakota""","""North Dakota State""","""North Florida""","""North Texas""","""Northeastern""","""Northern Arizona""","""Northern Colorado""","""Northern Illinois""","""Northern Iowa""","""Northern Kentucky""","""Northwestern""","""Northwestern State""","""Notre Dame""","""Oakland""","""Ohio""","""Ohio State""","""Oklahoma""","""Oklahoma State""","""Old Dominion""","""Ole Miss""","""Oral Roberts""","""Oregon""","""Oregon State""","""Pacific""","""Penn State""","""Pennsylvania""","""Pepperdine""","""Pittsburgh""","""Portland""","""Portland State""","""Prairie View A&M""","""Presbyterian""","""Princeton""","""Providence""","""Purdue""","""Purdue Fort Wayne""","""Quinnipiac""","""Radford""","""Rhode Island""","""Rice""","""Richmond""","""Rider""","""Robert Morris""","""Rutgers""","""Sacramento State""","""Sacred Heart""","""Saint Joseph's (PA)""","""Saint Louis""","""Saint Mary's""","""Sam Houston State""","""Samford""","""San Diego""","""San Diego State""","""San Francisco""","""San Jose State""","""Santa Clara""","""Seattle""","""Seton Hall""","""Siena""","""SIU-Edwardsville""","""SMU""","""South Alabama""","""South Carolina""","""South Carolina State""","""South Dakota""","""South Dakota State""","""South Florida""","""Southeast Missouri State""","""Southeastern Louisiana""","""Southern Illinois""","""Southern Miss""","""Southern University""","""Southern Utah""","""St. Bonaventure""","""St. Francis (BKN)""","""St. Francis (PA)""","""St. John's""","""St. Peter's""","""Stanford""","""Stephen F. Austin""","""Stetson""","""Stony Brook""","""Syracuse""","""TCU""","""Temple""","""Tennessee""","""Tennessee State""","""Tennessee Tech""","""Tennessee-Martin""","""Texas""","""Texas A&M""","""Texas A&M-CC""","""Texas Rio Grande Valley""","""Texas Southern""","""Texas State""","""Texas Tech""","""Texas-Arlington""","""Toledo""","""Towson""","""Troy""","""Tulane""","""Tulsa""","""UAB""","""UC Davis""","""UC Irvine""","""UC Riverside""","""UC Santa Barbara""","""UCF""","""UCLA""","""UMBC""","""UNC Asheville""","""UNC Greensboro""","""UNLV""","""USC""","""USC Upstate""","""Utah""","""Utah State""","""Utah Valley""","""UTEP""","""UTSA""","""Valparaiso""","""Vanderbilt""","""Vermont""","""Villanova""","""Virginia""","""Virginia Commonwealth""","""Virginia Military""","""Virginia Tech""","""Wagner""","""Wake Forest""","""Washington""","""Washington State""","""Weber State""","""West Virginia""","""Western Carolina""","""Western Illinois""","""Western Kentucky""","""Western Michigan""","""Wichita State""","""William & Mary""","""Winthrop""","""Wisconsin""","""Wofford""","""Wright State""","""Wyoming""","""Xavier""","""Yale""","""Youngstown State"""]
rem={i.text: i.get("value") for i in appa}
url2= "https://www.foxsports.com/"+ rem["Akron"]
for team_name in teams:
    url3 = "https://www.foxsports.com/" + rem[team_name]
    vanaja=r.get(url3)
    rajagopal=bs(vanaja.content,"html.parser")
    gopal= rajagopal.find_all("tr",{"class":"wisbb_teamScheduleRow"})
    _year=()
    tbd="TBD"
    times=()
    timerd=()
    a = [""" Abilene Christian""", """ Air Force""", """ Akron""", """ Alabama""", """ Alabama A&M""",
         """ Alabama State""", """ Albany""", """ Alcorn State""", """ American University""", """ Appalachian State""",
         """ Arizona""", """ Arizona State""", """ Arkansas""", """ Arkansas State""", """ Arkansas-Little Rock""",
         """ Arkansas-Pine Bluff""", """ Army""", """ Auburn""", """ Austin Peay""", """ Ball State""", """ Baylor""",
         """ Belmont""", """ Bethune-Cookman""", """ Binghamton""", """ Boise State""", """ Boston College""",
         """ Boston University""", """ Bowling Green""", """ Bradley""", """ Brown""", """ Bryant University""",
         """ Bucknell""", """ Buffalo""", """ Butler""", """ BYU""", """ Cal Poly""", """ Cal State Bakersfield""",
         """ Cal State Fullerton""", """ Cal State Northridge""", """ California""", """ California Baptist""",
         """ Campbell""", """ Canisius""", """ Central Arkansas""", """ Central Connecticut State""",
         """ Central Michigan""", """ Charleston""", """ Charleston Southern""", """ Charlotte""", """ Chattanooga""",
         """ Chicago State""", """ Cincinnati""", """ Citadel""", """ Clemson""", """ Cleveland State""",
         """ Coastal Carolina""", """ Colgate""", """ Colorado""", """ Colorado State""", """ Columbia""",
         """ Connecticut""", """ Coppin State""", """ Cornell""", """ Creighton""", """ Dartmouth""", """ Davidson""",
         """ Dayton""", """ Delaware""", """ Delaware State""", """ Denver""", """ DePaul""", """ Detroit Mercy""",
         """ Drake""", """ Drexel""", """ Duke""", """ Duquesne""", """ East Carolina""", """ East Tennessee State""",
         """ Eastern Illinois""", """ Eastern Kentucky""", """ Eastern Michigan""", """ Eastern Washington""",
         """ Elon""", """ Evansville""", """ Fairfield""", """ Fairleigh Dickinson""", """ Florida""",
         """ Florida A&M""", """ Florida Atlantic""", """ Florida Gulf Coast""", """ Florida International""",
         """ Florida State""", """ Fordham""", """ Fresno State""", """ Furman""", """ Gardner-Webb""",
         """ George Mason""", """ George Washington""", """ Georgetown""", """ Georgia""", """ Georgia Southern""",
         """ Georgia State""", """ Georgia Tech""", """ Gonzaga""", """ Grambling State""", """ Grand Canyon""",
         """ Green Bay""", """ Hampton""", """ Hartford""", """ Harvard""", """ Hawaii""", """ High Point""",
         """ Hofstra""", """ Holy Cross""", """ Houston""", """ Houston Baptist""", """ Howard""", """ Idaho""",
         """ Idaho State""", """ Illinois""", """ Illinois State""", """ Illinois-Chicago""", """ Incarnate Word""",
         """ Indiana""", """ Indiana State""", """ Iona""", """ Iowa""", """ Iowa State""", """ IUPUI""",
         """ Jackson State""", """ Jacksonville""", """ Jacksonville State""", """ James Madison""", """ Kansas""",
         """ Kansas City""", """ Kansas State""", """ Kennesaw State""", """ Kent State""", """ Kentucky""",
         """ La Salle""", """ Lafayette""", """ Lamar""", """ Lehigh""", """ Liberty""", """ Lipscomb""", """ LIU""",
         """ Long Beach State""", """ Longwood""", """ Louisiana Tech""", """ Louisiana-Lafayette""",
         """ Louisiana-Monroe""", """ Louisville""", """ Loyola (MD)""", """ Loyola Chicago""", """ Loyola Marymount""",
         """ LSU""", """ Maine""", """ Manhattan""", """ Marist""", """ Marquette""", """ Marshall""", """ Maryland""",
         """ Maryland-Eastern Shore""", """ Massachusetts""", """ Massachusetts-Lowell""", """ McNeese State""",
         """ Memphis""", """ Mercer""", """ Merrimack""", """ Miami (FL)""", """ Miami (OH)""", """ Michigan""",
         """ Michigan State""", """ Middle Tennessee""", """ Milwaukee""", """ Minnesota""", """ Mississippi State""",
         """ Mississippi Valley State""", """ Missouri""", """ Missouri State""", """ Monmouth""", """ Montana""",
         """ Montana State""", """ Morehead State""", """ Morgan State""", """ Mount St. Mary's""", """ Murray State""",
         """ N.J.I.T.""", """ Navy""", """ Nebraska""", """ Nebraska-Omaha""", """ Nevada""", """ New Hampshire""",
         """ New Mexico""", """ New Mexico State""", """ New Orleans""", """ Niagara""", """ Nicholls State""",
         """ Norfolk State""", """ North Alabama""", """ North Carolina""", """ North Carolina A&T""",
         """ North Carolina Central""", """ North Carolina State""", """ North Carolina-Wilmington""",
         """ North Dakota""", """ North Dakota State""", """ North Florida""", """ North Texas""", """ Northeastern""",
         """ Northern Arizona""", """ Northern Colorado""", """ Northern Illinois""", """ Northern Iowa""",
         """ Northern Kentucky""", """ Northwestern""", """ Northwestern State""", """ Notre Dame""", """ Oakland""",
         """ Ohio""", """ Ohio State""", """ Oklahoma""", """ Oklahoma State""", """ Old Dominion""", """ Ole Miss""",
         """ Oral Roberts""", """ Oregon""", """ Oregon State""", """ Pacific""", """ Penn State""",
         """ Pennsylvania""", """ Pepperdine""", """ Pittsburgh""", """ Portland""", """ Portland State""",
         """ Prairie View A&M""", """ Presbyterian""", """ Princeton""", """ Providence""", """ Purdue""",
         """ Purdue Fort Wayne""", """ Quinnipiac""", """ Radford""", """ Rhode Island""", """ Rice""", """ Richmond""",
         """ Rider""", """ Robert Morris""", """ Rutgers""", """ Sacramento State""", """ Sacred Heart""",
         """ Saint Joseph's (PA)""", """ Saint Louis""", """ Saint Mary's""", """ Sam Houston State""", """ Samford""",
         """ San Diego""", """ San Diego State""", """ San Francisco""", """ San Jose State""", """ Santa Clara""",
         """ Seattle""", """ Seton Hall""", """ Siena""", """ SIU-Edwardsville""", """ SMU""", """ South Alabama""",
         """ South Carolina""", """ South Carolina State""", """ South Dakota""", """ South Dakota State""",
         """ South Florida""", """ Southeast Missouri State""", """ Southeastern Louisiana""", """ Southern Illinois""",
         """ Southern Miss""", """ Southern University""", """ Southern Utah""", """ St. Bonaventure""",
         """ St. Francis (BKN)""", """ St. Francis (PA)""", """ St. John's""", """ St. Peter's""", """ Stanford""",
         """ Stephen F. Austin""", """ Stetson""", """ Stony Brook""", """ Syracuse""", """ TCU""", """ Temple""",
         """ Tennessee""", """ Tennessee State""", """ Tennessee Tech""", """ Tennessee-Martin""", """ Texas""",
         """ Texas A&M""", """ Texas A&M-CC""", """ Texas Rio Grande Valley""", """ Texas Southern""",
         """ Texas State""", """ Texas Tech""", """ Texas-Arlington""", """ Toledo""", """ Towson""", """ Troy""",
         """ Tulane""", """ Tulsa""", """ UAB""", """ UC Davis""", """ UC Irvine""", """ UC Riverside""",
         """ UC Santa Barbara""", """ UCF""", """ UCLA""", """ UMBC""", """ UNC Asheville""", """ UNC Greensboro""",
         """ UNLV""", """ USC""", """ USC Upstate""", """ Utah""", """ Utah State""", """ Utah Valley""", """ UTEP""",
         """ UTSA""", """ Valparaiso""", """ Vanderbilt""", """ Vermont""", """ Villanova""", """ Virginia""",
         """ Virginia Commonwealth""", """ Virginia Military""", """ Virginia Tech""", """ Wagner""",
         """ Wake Forest""", """ Washington""", """ Washington State""", """ Weber State""", """ West Virginia""",
         """ Western Carolina""", """ Western Illinois""", """ Western Kentucky""", """ Western Michigan""",
         """ Wichita State""", """ William & Mary""", """ Winthrop""", """ Wisconsin""", """ Wofford""",
         """ Wright State""", """ Wyoming""", """ Xavier""", """ Yale""", """ Youngstown State"""]
    b = ["""Abilene Christian Wildcats""", """Air Force Falcons""", """Akron Zips""", """Alabama Crimson Tide""",
         """Alabama A&M Bulldogs""", """Alabama State Hornets""", """Albany Great Danes""", """Alcorn State Braves""",
         """American University Eagles""", """Appalachian State Mountaineers""", """Arizona Wildcats""",
         """Arizona State Sun Devils""", """Arkansas Razorbacks""", """Arkansas State Red Wolves""",
         """Arkansas-Little Rock Trojans""", """Arkansas-Pine Bluff Golden Lions""", """Army Black Knights""",
         """Auburn Tigers""", """Austin Peay Governors""", """Ball State Cardinals""", """Baylor Bears""",
         """Belmont Bruins""", """Bethune-Cookman Wildcats""", """Binghamton Bearcats""", """Boise State Broncos""",
         """Boston College Eagles""", """Boston University Terriers""", """Bowling Green Falcons""",
         """Bradley Braves""", """Brown Bears""", """Bryant University Bulldogs""", """Bucknell Bison""",
         """Buffalo Bulls""", """Butler Bulldogs""", """BYU Cougars""", """Cal Poly Mustangs""",
         """Cal State Bakersfield Roadrunners""", """Cal State Fullerton Titans""", """Cal State Northridge Matadors""",
         """California Golden Bears""", """California Baptist Lancers""", """Campbell Fighting Camels""",
         """Canisius Golden Griffins""", """Central Arkansas Bears""", """Central Connecticut State Blue Devils""",
         """Central Michigan Chippewas""", """Charleston Cougars""", """Charleston Southern Buccaneers""",
         """Charlotte 49ERS Schedule""", """Chattanooga Mocs""", """Chicago State Cougars""", """Cincinnati Bearcats""",
         """Citadel Bulldogs""", """Clemson Tigers""", """Cleveland State Vikings""",
         """Coastal Carolina Chanticleers""", """Colgate Raiders""", """Colorado Buffaloes""",
         """Colorado State Rams""", """Columbia Lions""", """Connecticut Huskies""", """Coppin State Eagles""",
         """Cornell Big Red""", """Creighton Blue Jays""", """Dartmouth Big Green""", """Davidson Wildcats""",
         """Dayton Flyers""", """Delaware Fightin Blue Hens""", """Delaware State Hornets""", """Denver Pioneers""",
         """Depaul Blue Demons""", """Detroit Mercy Titans""", """Drake Bulldogs""", """Drexel Dragons""",
         """Duke Blue Devils""", """Duquesne Dukes""", """East Carolina Pirates""",
         """East Tennessee State Buccaneers""", """Eastern Illinois Panthers""", """Eastern Kentucky Colonels""",
         """Eastern Michigan Eagles""", """Eastern Washington Eagles""", """Elon Phoenix""",
         """Evansville Purple Aces""", """Fairfield Stags""", """Fairleigh Dickinson Knights""", """Florida Gators""",
         """Florida A&M Rattlers""", """Florida Atlantic Owls""", """Florida Gulf Coast Eagles""",
         """Florida International Golden Panthers""", """Florida State Seminoles""", """Fordham Rams""",
         """Fresno State Bulldogs""", """Furman Paladins""", """Gardner-Webb Runnin Bulldogs""",
         """George Mason Patriots""", """George Washington Colonials""", """Georgetown Hoyas""", """Georgia Bulldogs""",
         """Georgia Southern Eagles""", """Georgia State Panthers""", """Georgia Tech Yellow Jackets""",
         """Gonzaga Bulldogs""", """Grambling State Tigers""", """Grand Canyon Antelopes""", """Green Bay Phoenix""",
         """Hampton Pirates""", """Hartford Hawks""", """Harvard Crimson""", """Hawaii Warriors""",
         """High Point Panthers""", """Hofstra Pride""", """Holy Cross Crusaders""", """Houston Cougars""",
         """Houston Baptist Huskies""", """Howard Bison""", """Idaho Vandals""", """Idaho State Bengals""",
         """Illinois Fighting Illini""", """Illinois State Redbirds""", """Illinois-Chicago Flames""",
         """Incarnate Word Cardinals""", """Indiana Hoosiers""", """Indiana State Sycamores""", """Iona Gaels""",
         """Iowa Hawkeyes""", """Iowa State Cyclones""", """Iupui Jaguars""", """Jackson State Tigers""",
         """Jacksonville Dolphins""", """Jacksonville State Gamecocks""", """James Madison Dukes""",
         """Kansas Jayhawks""", """Kansas City Roos""", """Kansas State Wildcats""", """Kennesaw State Owls""",
         """Kent State Golden Flashes""", """Kentucky Wildcats""", """La Salle Explorers""", """Lafayette Leopards""",
         """Lamar Cardinals""", """Lehigh Mountain Hawks""", """Liberty Flames""", """Lipscomb Bisons""",
         """Liu Sharks""", """Long Beach State Beach""", """Longwood Lancers""", """Louisiana Tech Bulldogs""",
         """Louisiana-Lafayette Ragin' Cajuns""", """Louisiana-Monroe Warhawks""", """Louisville Cardinals""",
         """Loyola Maryland Greyhounds""", """Loyola Chicago Ramblers""", """Loyola Marymount Lions""",
         """Lsu Tigers""", """Maine Black Bears""", """Manhattan Jaspers""", """Marist Red Foxes""",
         """Marquette Golden Eagles""", """Marshall Thundering Herd""", """Maryland Terrapins""",
         """Maryland-Eastern Shore Hawks""", """Massachusetts Minutemen""", """Massachusetts-Lowell River Hawks""",
         """McNeese State Cowboys""", """Memphis Tigers""", """Mercer Bears""", """Merrimack Warriors""",
         """Miami (Fl) Hurricanes""", """Miami (Oh) RedHawks""", """Michigan Wolverines""",
         """Michigan State Spartans""", """Middle Tennessee Blue Raiders""", """Milwaukee Panthers""",
         """Minnesota Golden Gophers""", """Mississippi State Bulldogs""", """Mississippi Valley State Delta Devils""",
         """Missouri Tigers""", """Missouri State Bears""", """Monmouth Hawks""", """Montana Grizzlies""",
         """Montana State Bobcats""", """Morehead State Eagles""", """Morgan State Bears""",
         """Mount St. Mary's Mountaineers""", """Murray State Racers""", """N.j.i.t. Highlanders""",
         """Navy Midshipmen""", """Nebraska Cornhuskers""", """Nebraska-Omaha Mavericks""", """Nevada Wolf Pack""",
         """New Hampshire Wildcats""", """New Mexico Lobos""", """New Mexico State Aggies""",
         """New Orleans Privateers""", """Niagara Purple Eagles""", """Nicholls State Colonels""",
         """Norfolk State Spartans""", """North Alabama Lions""", """North Carolina Tar Heels""",
         """North Carolina A&T Aggies""", """North Carolina Central Eagles""", """North Carolina State Wolfpack""",
         """North Carolina-Wilmington Seahawks""", """North Dakota Fighting Hawks""", """North Dakota State Bison""",
         """North Florida Ospreys""", """North Texas Mean Green""", """Northeastern Huskies""",
         """Northern Arizona Lumberjacks""", """Northern Colorado Bears""", """Northern Illinois Huskies""",
         """Northern Iowa Panthers""", """Northern Kentucky Norse""", """Northwestern Wildcats""",
         """Northwestern State Demons""", """Notre Dame Fighting Irish""", """Oakland olden Grizzlies""",
         """Ohio Bobcats""", """Ohio State Buckeyes""", """Oklahoma Sooners""", """Oklahoma State Cowboys""",
         """Old Dominion Monarchs""", """Ole Miss Rebels""", """Oral Roberts Golden Eagles""", """Oregon Ducks""",
         """Oregon State Beavers""", """Pacific Tigers""", """Penn State Nittany Lions""", """Pennsylvania Quakers""",
         """Pepperdine Waves""", """Pittsburg Panthers""", """Portland Pilots""", """Portland State Vikings""",
         """Prairie View A&M Panthers""", """Presbyterian Blue Hose""", """Princeton Tigers""", """Providence Friars""",
         """Purdue Boilermakers""", """Purdue Fortt Wayne Mastodons""", """Quinnipiac Bobcats""",
         """Radford Highlanders""", """Rhode Island Rams""", """Rice Owls""", """Richmond Spiders""",
         """Rider Broncs""", """Robert Morris Colonials""", """Rutgers Scarlet Knights""",
         """Sacramento State Hornets""", """Sacred Heart Pioneers""", """Saint Joseph's (PA) Hawks""",
         """Saint Louis Billikens""", """Saint Mary's Gaels""", """Sam Houston State Bearkats""",
         """Samford Bulldogs""", """San Diego Toreros Schedule""", """San Diego State Aztecs""",
         """San Francisco Dons""", """San Jose State Spartans""", """Santa Clara Broncos""", """Seattle Redhawks""",
         """Seton Hall Pirates""", """Siena Saints""", """Siu-Edwardsville Cougars""", """Smu Mustangs Schedule""",
         """South Alabama Jaguars""", """South Carolina Gamecocks""", """South Carolina State Bulldogs""",
         """South Dakota Coyotes""", """South Dakota State Jackrabbits""", """South Florida Bulls""",
         """Southeast Missouri State Redhawks""", """Southeastern Louisiana Lions""", """Southern Illinois Salukis""",
         """Southern Miss Golden Eagles""", """Southern University Jaguars""", """Southern Utah Thunderbirds""",
         """St. Bonaventure Bonnies""", """St. Francis (BKN) Terriers""", """St. Francis (PA) Red Flash""",
         """St. John's Red Storm""", """St. Peter's Peacocks""", """Stanford Cardinal""",
         """Stephen F. Austin Lumberjacks""", """Stetson Hatters""", """Stony Brook Seawolves""", """Syracuse Orange""",
         """Tcu Horned Frogs""", """Temple Owls""", """Tennessee Volunteers""", """Tennessee State Tigers""",
         """Tennessee Tech Golden Eagles""", """Tennessee-Martin Skyhawks""", """Texas Longhorns""",
         """Texas A&M Aggies""", """Texas A&M-CC Islanders""", """Texas Rio Grande Valley Vaqueros""",
         """Texas Southern Tigers""", """Texas State Bobcats""", """Texas Tech Red Raiders""",
         """Texas-arlington Mavericks""", """Toledo Rockets""", """Towson Tigers""", """Troy Trojans""",
         """Tulane Green Wave""", """Tulsa Golden Hurricane""", """Uab Blazers""", """Uc Davis Aggies""",
         """Uc Irvine Anteaters""", """Uc Riverside Highlanders""", """Uc Santa Barbara Gauchos""", """Ucf Knights""",
         """Ucla Bruins""", """Umbc Retrievers""", """Unc Asheville Bulldogs""", """Unc Greensboro Spartans""",
         """Unlv Rebels""", """Usc Trojans""", """Usc Upstate Spartans""", """Utah Utes""", """Utah State Aggies""",
         """Utah Valley Wolverines""", """Utep Miners""", """Utsa Roadrunners""", """Valparaiso Crusaders""",
         """Vanderbilt Commodores""", """Vermont Catamounts""", """Villanova Wildcats""", """Virginia Cavaliers""",
         """Virginia Commonwealth Rams""", """Virginia Military Keydets""", """Virginia Tech Hokies""",
         """Wagner Seahawks""", """Wake Forest Demon Deacons""", """Washington Huskies""",
         """Washington State Cougars""", """Weber State Wildcats""", """West Virginia Mountaineers""",
         """Western Carolina Catamounts""", """Western Illinois Leathernecks""", """Western Kentucky Hilltoppers""",
         """Western Michigan Broncos""", """Wichita State Shockers""", """William & Mary Tribe""",
         """Winthrop Eagles""", """Wisconsin Badgers""", """Wofford Terriers""", """Wright State Raiders""",
         """Wyoming Cowboys""", """Xavier Musketeers""", """Yale Bulldogs""", """Youngstown State Penguins"""]
    c = ["""ABAP""", """AAMU""", """AC""", """AFA""", """AKR""", """ALA""", """ALBY""", """ALC""", """ALCN""",
         """ALMA""", """ALST""", """AMCC""", """AMER""", """APP""", """AQC""", """ARIZ""", """ARK""", """ARKM""",
         """ARKT""", """ARMY""", """ARPB""", """ARST""", """ASU""", """AU""", """AUB""", """AUIN""", """AUM""",
         """AVE""", """AVU""", """BAC""", """BALL""", """BAY""", """BC""", """BEL""", """BENU""", """BETH""",
         """BGSU""", """BING""", """BLMT""", """BLST""", """BOBJ""", """BPC""", """BRAD""", """BRES""", """BRWN""",
         """BRY""", """BRYC""", """BRYN""", """BSC""", """BSU""", """BU""", """BUCK""", """BUFF""", """BUT""",
         """BVC""", """BWAT""", """BYU""", """CAIR""", """CAL""", """CALD""", """CALL""", """CAMP""", """CAN""",
         """CARK""", """CARV""", """CBAP""", """CBU""", """CC""", """CCAR""", """CCCB""", """CCHI""", """CCLA""",
         """CCNJ""", """CCSU""", """CCU""", """CCWI""", """CHA""", """CHAR""", """CHAT""", """CHC""", """CHS""",
         """CHSO""", """CHST""", """CIN""", """CINC""", """CIT""", """CIU""", """CLEM""", """CLEV""", """CLMB""",
         """CMU""", """CNTX""", """CNU""", """COFC""", """COKER""", """COLG""", """COLO""", """CONN""", """COOK""",
         """COPP""", """COR""", """CORC""", """CP""", """CPEN""", """CRC""", """CREI""", """CRRY""", """CSB""",
         """CSE""", """CSF""", """CSLA""", """CSN""", """CSU""", """CSUS""", """CSUSB""", """CTC""", """CUMB""",
         """CUMI""", """CUWV""", """CVHB""", """DART""", """DAV""", """DAY""", """DCC""", """DEFC""", """DEL""",
         """DEN""", """DEP""", """DET""", """DOAN""", """DPORT""", """DREX""", """DRKE""", """DSU""", """DUKE""",
         """DUQ""", """EC""", """ECCC""", """ECNT""", """ECU""", """EIU""", """EKY""", """ELON""", """ELZT""",
         """EMCR""", """EMHE""", """EMU""", """ENMU""", """ERSK""", """ESC""", """ETB""", """ETSU""", """EUP""",
         """EVAN""", """EWU""", """FAIR""", """FAMU""", """FARM""", """FAU""", """FC""", """FDU""", """FDUF""",
         """FGCU""", """FHU""", """FISK""", """FIT""", """FIU""", """FLA""", """FLAC""", """FMSU""", """FMU""",
         """FNU""", """FOR""", """FPU""", """FRAN""", """FRES""", """FSU""", """FUR""", """GALL""", """GASO""",
         """GAST""", """GB""", """GBC""", """GC""", """GCU""", """GMU""", """GNV""", """GONZ""", """GORD""", """GOUC""",
         """GRAM""", """GRC""", """GT""", """GTWN""", """GU""", """GW""", """HALL""", """HAMP""", """HART""",
         """HARV""", """HASK""", """HAW""", """HBU""", """HC""", """HDRX""", """HEID""", """HFC""", """HIRAM""",
         """HNU""", """HOF""", """HOU""", """HOW""", """HP""", """HPU""", """HRTW""", """HSC""", """HTU""", """IDHO""",
         """IDST""", """ILL""", """ILST""", """ILW""", """IND""", """INST""", """IONA""", """IOWA""", """ISU""",
         """IUK""", """IUN""", """IUPU""", """IUSB""", """IW""", """JAC""", """JARV""", """JKST""", """JMU""",
         """JOES""", """JOHN""", """JUDS""", """JVST""", """JWCO""", """JWNC""", """JWRI""", """KCU""", """KEAN""",
         """KEIS""", """KENN""", """KENT""", """KSU""", """KU""", """KY-W""", """LAF""", """LAM""", """LAS""",
         """LBSU""", """LC""", """LEH""", """LESL""", """LETU""", """LIB""", """L-IL""", """LINW""", """LIP""",
         """LIU""", """L-MD""", """LMU""", """LONG""", """LOU""", """LPC""", """LSU""", """LT""", """LUNO""",
         """LUTH""", """LYNS""", """MABO""", """MACU""", """MALO""", """MAN""", """MAR""", """MARQ""", """MARY""",
         """MASS""", """MASSL""", """MC""", """MCKN""", """MCNS""", """MD""", """ME""", """MEC""", """MEM""", """MEN""",
         """MER""", """MGC""", """MHU""", """MIA""", """MICH""", """MID""", """MI-D""", """MIDL""", """MILL""",
         """MILW""", """MINN""", """MISE""", """MISS""", """MIT""", """MIZZ""", """MMA""", """MMU""", """MNCH""",
         """M-OH""", """MONM""", """MONT""", """MORE""", """MORG""", """MOSU""", """MRMK""", """MRSH""", """MRST""",
         """MSJ""", """MSM""", """MSST""", """MSTV""", """MSU""", """MSUN""", """MT""", """MTM""", """MTST""",
         """MTU""", """MULT""", """MURR""", """MVC""", """MVSU""", """MZBU""", """MZST""", """NAU""", """NAVY""",
         """NAZ""", """NC""", """NCAT""", """NCCU""", """NCST""", """NCU""", """NCW""", """ND""", """NDNU""",
         """NDSU""", """NE""", """NEB""", """NEBW""", """NEOM""", """NEV""", """NGU""", """NIAG""", """NICH""",
         """NIU""", """NJIT""", """NKU""", """NMHU""", """NMSU""", """NNMX""", """NORC""", """NORF""", """NPU""",
         """NW""", """NWOH""", """NWST""", """NYCL""", """NYIT""", """NYON""", """NYPO""", """OAK""", """OAKC""",
         """OBER""", """ODU""", """OHCC""", """OHIO""", """OHNU""", """OKCU""", """OKLA""", """OKST""", """OLLU""",
         """ONAZ""", """ORE""", """ORST""", """ORU""", """OSU""", """OTT""", """PAC""", """PAOR""", """PBA""",
         """PBC""", """PEAY""", """PENN""", """PEPP""", """PERU""", """PFW""", """PIE""", """PITT""", """PLUT""",
         """PMC""", """PORT""", """PQC""", """PRE""", """PRIN""", """PROV""", """PRST""", """PSU""", """PSWB""",
         """PSY""", """PU""", """PUC""", """PUN""", """PUR""", """PV""", """QU""", """QUIN""", """RAD""", """RAND""",
         """RED""", """REGU""", """REIN""", """RHOC""", """RICE""", """RICH""", """RID""", """RIO""", """RMC""",
         """RMU""", """ROCK""", """ROSE""", """RSU""", """RUST""", """RUTC""", """RUTG""", """SAC""", """SAIC""",
         """SAM""", """SBON""", """SCAR""", """SCS""", """SCST""", """SCU""", """SCUS""", """SDAK""", """SDCC""",
         """SDST""", """SDSU""", """SEA""", """SEBC""", """SELA""", """SEMO""", """SF""", """SFA""", """SFIL""",
         """SFNY""", """SFPA""", """SFSU""", """SHC""", """SHEN""", """SHRT""", """SHSU""", """SHU""", """SIE""",
         """SIH""", """SIMP""", """SIU""", """SIUE""", """SJSU""", """SJU""", """SK""", """SLU""", """SMC""",
         """SMCM""", """SMU""", """SNST""", """SOU""", """SOWU""", """SPAL""", """SPC""", """STAN""", """STET""",
         """STMU""", """STON""", """STTX""", """STUB""", """SUNO""", """SUNYP""", """SUNYPI""", """SUU""", """SWBU""",
         """SWCU""", """SWTX""", """SYR""", """TAMI""", """TAS""", """TBC""", """TC""", """TCU""", """TEM""",
         """TENN""", """TEX""", """TFC""", """THIE""", """THOM""", """TICC""", """TIFF""", """TLSA""", """TLU""",
         """TNAZ""", """TNST""", """TNTC""", """TNW""", """TOL""", """TOWS""", """TRIN""", """TROY""", """TRUE""",
         """TTU""", """TULN""", """TWU""", """TXAM""", """TXD""", """TXSO""", """TXST""", """UAB""", """UAFS""",
         """UALR""", """UAV""", """UC""", """UCD""", """UCF""", """UCI""", """UCLA""", """UCM""", """UCOK""",
         """UCRV""", """UCSB""", """UCSC""", """UGA""", """UIC""", """UIS""", """UK""", """ULL""", """ULM""", """UM""",
         """UMBC""", """UMES""", """UMKC""", """UMSL""", """UMW""", """UNA""", """UNC""", """UNCA""", """UNCG""",
         """UNCO""", """UNCW""", """UND""", """UNEK""", """UNF""", """UNH""", """UNI""", """UNLV""", """UNM""",
         """UNO""", """UNT""", """UOP""", """UPS""", """URB""", """URI""", """USA""", """USC""", """USD""", """USF""",
         """USM""", """USMMA""", """USU""", """UTA""", """UTAH""", """UTAMPA""", """UTEP""", """UTM""", """UTPB""",
         """UTRGV""", """UTSA""", """UVA""", """UVAW""", """UVF""", """UVM""", """UVU""", """UWS""", """VALP""",
         """VAN""", """VCU""", """VILL""", """VMI""", """VT""", """VU""", """WAG""", """WAKE""", """WALL""", """WASH""",
         """WAU""", """WAYB""", """WBC""", """WC""", """WCBC""", """WCF""", """WCU""", """WEB""", """WEBB""",
         """WEST""", """WEW""", """WFU""", """WHIT""", """WICH""", """WIDE""", """WILU""", """WIN""", """WIS""",
         """WIU""", """WJ""", """WKU""", """WLMT""", """WM""", """WMPA""", """WMU""", """WNMU""", """WOF""", """WPU""",
         """WRST""", """WSC""", """WSU""", """WVU""", """WYO""", """XAV""", """XULA""", """YALE""", """YSU"""]
    d = ["""Arlington Baptistpatriots""", """Albama A&M Bulldogs""", """Abilene Christian Wildcats""",
         """Air Force Falcons""", """Akron Zips""", """Alabama Crimson Tide""", """Albany Great Danes""",
         """Allice Lloyd Eagles""", """Alcorn State Hornets""", """Alma Scots""", """Alabama State Hornets""",
         """Texas A&M-Ccislanders""", """American University Eagles """, """Appalachian State Mountaineers""",
         """Aquanas College Saints""", """Arizona Wildcats""", """Arkansasrazorbacks""",
         """Arkansas-Monticello Boll Weevils""", """Arkanasas Tech Wonder Boys""", """Armyblack Knights""",
         """Arkansas-Pine Bluffgolden Lions """, """Arkansas State Red Wolves """, """Arizona Statesun Devils""",
         """St. Louis College Of Pharmacy Eutectics""", """Auburn Tigers""", """Anderson (In) Ravens""",
         """Auburn-Montgomery Warharks""", """Avemaria Gyrenes""", """Avila Eagles""", """Belmont Abbey Crusaders""",
         """Ball State Cardinals""", """Baylor Bears""", """Boston College Eagles""", """Belmont Bruins""",
         """Benedictine At Mesa Redhawks""", """Bethesda Flames""", """Bowling Green Falcons""",
         """Binghamton Bearcats""", """Blue Mountain Toppers """, """Bluefield State Blues """, """Bob Jones Bruins""",
         """Brewton-Parker College Barons""", """Bradley Braves""", """Brescia Bearcats """, """Brown Bears """,
         """Bryant University Bulldogs """, """Bryan College Lions """, """Bryn Athyn Lions""",
         """Birmingham-Southern Panthers""", """Boise State Broncos""", """Boston University Terriers""",
         """Bucknell Bison""", """Buffalo Bulls""", """Butler Bulldogs """, """Brevard College Tornadoes""",
         """Bridgewater Eagles""", """Byu Cougars""", """Cairn Highlanders""", """California Golden Bears""",
         """Caldwell Cougars""", """California Lutheran Kingsmen""", """Campbell Fighting Camels""",
         """Cansius Golden Griffins""", """Central Arkansas Bears""", """Carver Cougars""",
         """Champion Christian College Tigers""", """California Baptist Lancers """, """Crown College Storm""",
         """Coastal Carolina Chanticleers""", """Central Christian College Of The Bible Saints""",
         """Concordia-Chicago Cougars """, """Centenary College Of Louisiana Gentlemen""",
         """Centenary (Nj) Cyclones""", """Central Connecticut State Bluedevils""", """Colorado Christian Cougars""",
         """Concordia (Wi) Falcons""", """Chaminade Silverswords""", """Charlotte 49Ers""", """Chattanooga Mocs""",
         """Chestnut Hill Griffins""", """Chicago State Cougars""", """Charleston Southern Buccaneers""",
         """Christendom Crusaders""", """Cincinnati Bearcats""", """Cincinnati Clermont Cougars""",
         """Citadel Bulldogs""", """Columbia International Rams""", """Clemson Tigers""", """Cleveland State Vikings""",
         """Columbia Lions""", """Central Michigan Chippewas""", """Concordia (Tx) Tornadoes""",
         """Carson-Newman Eagles""", """Charleston Cougars""", """Coker Cobras""", """Colgate Raiders""",
         """Colorado Buffaloes""", """Connecticut Huskies """, """Bethune-Cookman Wildcats""",
         """Coppin State Eagles""", """Cornell Big Red""", """Cornell College Rams""", """Cal Poly Mustangs""",
         """Central Penn College Knights""", """Crowley'S Ridge  Pioneers""", """Creighton Bluejays""",
         """Curry College Colonels""", """Cal State Bakersfield Roadrunners """, """Saint Elizabeth Screaming Eagles""",
         """Cal State Fullerton Titans""", """Cal State Los Angeles Golden Eagles """,
         """Cal State Northridge Matadors""", """Colorado State""", """Stanislaus State Warriors""",
         """Cal State San Bernardino Coyotes """, """Connecticut College Camels""", """Cumberland Phoenix""",
         """Concordia (Mi) Cardinals""", """Concord (Wv)Mountain Lions""", """Campbellsville-Harrodsburg Tigers """,
         """Dartmouth Big Green""", """Davidson Wildcats""", """Dayton Flyers""", """Dallas Christiancrusaders""",
         """Defiance Yellow Jackets""", """Delaware Fightin Blue Hens """, """Denverpioneers""",
         """Depaul Blue Demons""", """Detroit Mercy Titans""", """Doane Tigers """, """Davenport Panthers""",
         """Drexel Dragonsdrexeldragons""", """Drakebulldogs""", """Delware State Hornets""", """Duke Blue Devils""",
         """Duquesnedukes""", """Eureka Red Devils""", """Ecclesia Royals""", """East Central Tigers""",
         """East Carolina Pirates""", """Eastern Illinois Panthers""", """Eastern Kentucky Colonels""",
         """Elon Pheonix""", """Elizabethtown Blue Jays""", """Emerson Lions""", """Emory & Henry Wasps""",
         """Eastern Michigan Eagles""", """Eastern New Mexico Greyhounds""", """Erskine Flying Fleet""",
         """Evergreen State Geoducks """, """East Texas Baptist Tigers""", """East Tennessee State Buccaneers""",
         """Edinboro Fighting Scots""", """Evansville Purpleaces""", """Eastern Washington Eagles""",
         """Fairfield Stags""", """Florida A&M Rattlers""", """Farmingdalestate Rams""", """Florida Atlanticowls""",
         """Ferrum Panthers""", """Fairleigh Dickinson Knights""", """Fdu-Florham Devils""",
         """Florida Gulf Coast Eagles:""", """Freed-Hardeman Lions""", """Fisk Bulldogs""",
         """Florida Institute Of Technology Panthers""", """Florida International Golden Panthers""",
         """Florida Gators""", """Florida College Falcons""", """Fairmont State Fighting Falcons""",
         """Florida Memorial Fighting Lions""", """Florida National Conquistadors""", """Fordham Rams""",
         """Fresno Pacific Sunbirds""", """Francis University Of Stetbenville Barons""", """Fresno State Bulldogs""",
         """Florida State """, """Furman Paladins """, """Gallaudet Bison""", """Georgia Southern Eagles""",
         """Georgia State Panthers""", """Green Bay Phoenix""", """Gettysburg Bullets""", """Grand Canyon Antelopes""",
         """Georgian Court Lions""", """George Mason Patriots""", """Geneva Golden Tornadoes""", """Gonzaga Bulldogs""",
         """Gordon College Fighting Scots""", """Goucher Gophers""", """Grambling Statetigers""",
         """Greensboro Pride""", """Georgia Tech Yellow Jackets""", """Georgetown Hoyas""", """Gannon Golden Knights""",
         """George Washington Colonials""", """Seton Hall Pirates""", """Hampton Pirates""", """Hartford Hawks """,
         """Harvard Crimson""", """Haskell Indians""", """Hawaii Warriors""", """Houston Baptist Huskies""",
         """Holy Cross Crusaders""", """Hendrix Warriors""", """Heidelberg Student Princes""",
         """Holy Family College Lakers""", """Hiram Terriers""", """Holy Names Hawks""", """Hofstra Pride""",
         """Houston Cougars""", """Howard Bison""", """Highpoint Panthers""", """Howard Payneyellow Jackets""",
         """Hartwick Hawks""", """Hampden-Sydney College Tigers""", """Huston-Tillotson Rams""", """Idaho Vandals""",
         """Idaho Statebengals""", """Illinois Fighting Illini""", """Illinois State Redbirds""",
         """Illinois Wesleyan""", """Indiana Hoosiers""", """Indian State Sycamores""", """Iona Gaels""",
         """Iowa Hawkeyes""", """Iowa State Cyclones""", """Indiana-Kokomo Cougars""",
         """Indiana -Northwest Redhawks""", """Iupui Jaguars""", """Indiana University South Bend Titans""",
         """Incarnate Word Cardinals""", """Jacksonville Dolphins""", """Jarvis Christian Bulldogs""",
         """Jackson Statetigers""", """James Madison""", """Saint Joseph'S (Pa) Hawks""", """Johnson (Fl) Sons""",
         """Judson Eagles""", """Jacksonville Stategamecocks""", """Johnson & Wales (Co)Wildcats""",
         """Johnson % Wales(Nc) Wildcats""", """Johnson & Wales (Ri)Wildcats""", """Kentucky Chtistian Knights""",
         """Kean Cougars""", """Keiser Seahawks""", """Kennesaw State Owls""", """Kent Stategolden Flashes""",
         """Kansas State Wildcats""", """Kansas Jayhawks""", """Kentucky Wesleyan Panthers""",
         """Lafayette Leopards """, """Lamarcardinals""", """La Salle Explorers""", """Long Beach State Beach""",
         """Louisiana College Wildcats""", """Lehigh Mountain Hawks""", """Lesley Lynx""",
         """Letourneau Yellowjackets""", """Liberty Flames""", """Loyola Chicago Ramblers""", """Lindenwood Lions""",
         """Lipscomb Bisons""", """Liu Sharks""", """Loyola (Md) Greyhounds""", """Loyola Marymountlions""",
         """Longwood Lancers""", """Louisville cardinals""", """Life Pacific College Warriors""", """Lsu Tigers""",
         """Louisiana Tech Bulldogs""", """Loyola (No) Wolfpack""", """Luther College Norse""",
         """Lyndonstate Hornets""", """Massachusetts-Boston Beacons""", """Mid-Atlantic Christian Mustangs""",
         """Malonepioneers""", """Manhattan Jaspers""", """Martin Methodist Redhawks""", """Marquette Golden Eagles""",
         """Maryville (Mo) Saints""", """Massachusettsminutemen""", """Massachusetts-Lowell River Hawks""",
         """Morehouse Maroon Tigers""", """Mckendree Bearcats""", """Mcneese Statecowboys""", """Maryland Terrapins""",
         """Maine Black Bears""", """Medgar Evers College Cougars""", """Memphis Tigers """, """Menlo Oaks""",
         """Mercer Bears""", """Middle Georgia State Knights""", """Mars Hill Lions""", """Miami (Fl)Hurricanes""",
         """Michigan Wolverines""", """Midway Eagles""", """Michigan-Dearborn Wolverines""", """Midland Warriors""",
         """Milligan Buffaloes""", """Mil Waukee Panthers""", """Minnesota Golden Gophers""",
         """Misericordia Cougars""", """Ole Missrebels""", """Mit Engineers""", """Missouri Tigers""",
         """Maine Maritime Academy Mariners""", """Marymount Saints""", """Manchester Spartans""",
         """Miami (Oh)Redhawks""", """Monmouth Hawks""", """Montana Grizzlies""", """Morehead State Eagles""",
         """Morganstate Bears""", """Missouri State Bears""", """Merrimackwarriors""", """Marshallthundering Herd""",
         """Marist Red Foxes""", """Mount St.Joseph Lions""", """Mount St. Mary'S Mountaineers""",
         """Mississippi State Bullgogs""", """Mount Saint Vincent Dolphins""", """Michigan State Spartans""",
         """Montana State Northern Skylights""", """Montana Tech Orediggers""", """Mount Marty Lancers""",
         """Montana State Bobcats """, """Middle Tennessee Blueraiders""", """Multnomah Lions""",
         """Murray State Racers""", """Maryville (Tn) Scots""", """Mississippi Valley Statedelta Devils""",
         """Missouri Baptist Spartans""", """Missouri S&T Miners""", """Northern Arizona Lumberjacks""",
         """Navy Midshipmen""", """Nazareth (Ny) Golden Flyers""", """Newberry Wolves""",
         """North Carolina A&T Aggies""", """North Carolina Central Eagles""", """North Carolina State Wolfpack""",
         """North Central University Rams""", """Nc Wesleyan Battling Bishops""", """Notre Damefighting Irish""",
         """Notre Dame De Namur Argonauts""", """North Dakota State Bison""", """North Eastern Huskies""",
         """Nebraska Cornhuskers""", """Nebraska Wesleyan Prarie Wolves""", """Nebraska-Omaha Mavericks""",
         """Nevadawolf Pack""", """North Greenville Crusaders""", """Niagara Purple Eagles""",
         """Nicholls Statecolonels """, """Northern Illinoishuskies """, """N.J.I.T. Highlanders """,
         """Northern Kentucky Norse """, """New Mexico Highlands Cowboys""", """New Mexico State Aggies""",
         """Northern New Mexic0 Eagles""", """Northland College Lumberjacks""", """Norfolk State Spartans""",
         """North Park Vikings""", """North Western Wildcats""", """Northwestern Ohio Racers""",
         """Northwestern Statedemons""", """Suny-Cortland Red Dragons""", """New York Institute Of Technology Bears""",
         """Sun-Oneonta Red Dragons""", """Suny-Potsdam Bears""", """Oakland Golden Grizzlies""",
         """Oakland City Mighty Oaks""", """Oberlin Yeomen""", """Old Dominion Monarchs""",
         """Ohio University Chillcothe Hilltoppers""", """Ohiobobcats""", """Ohio Northern Polar Bears""",
         """Oklahoma Christian Eagles""", """Oklahoma Sooners""", """Oklahoma State Cowboys""",
         """Our Lady Of The Lakesaints""", """Olivet Nazarene Tigers""", """Oregon Ducks""", """Oregon Statebeavers""",
         """Oral Roberts Golden Eagles""", """Ohio State Buckeyes""", """Ottawa Spirit""", """Pacific Tigers """,
         """Pacific (Or) Boxers""", """Palmbeach Atlantic Sailfish""", """Portland Bible College Wildcats""",
         """Austin Peay Governors""", """Pennsylvaniaquakers """, """Pepperdinewaves""", """Peru State Bobcats""",
         """Purddue Fort Wayne Mastodons""", """Piedmont Lions""", """Pittsburgh Panthers""",
         """Pacific Lutheran Lutes""", """Pine Manor Gators""", """Portland Pilots""", """Paul Quinn College Tigers""",
         """Presbyterian Blue Hose""", """Princeton Tigers""", """Providence Friars""", """Portland State Vikings""",
         """Penn State Nittany Lions""", """Penn State Wilkes-Barre Nittany Lions""",
         """Penn State York Nittany Lions""", """Pfeiffer Falcons""", """Pacific Union College Pioneers""",
         """Purdue University Northwest Pride""", """Purdue Boilermakers""", """Praire View A&M Panthers""",
         """Quincy Hawks""", """Quinnipiac Bobcats""", """Radford Highlanders""", """Randolph Wildcats""",
         """Redlands Bulldogs""", """Regent University Royals""", """Reinhardt Eagles""", """Rhodes Lynx""",
         """Rice Owls """, """Richmondspiders""", """Rider Broncs""", """Rio Grande Red Storm""",
         """Rocky Mountain College Battlin' Bears""", """Robert Morris Colonials""", """Rockford Regents""",
         """Rosemont Ravens""", """Rogers State Hillcats""", """Rust College Bearcats""",
         """Rutgers-Camden Scarlet Raptors""", """Rutgers Scarlet Knights""", """Sacramento Statehornets""",
         """Sagu American Indian College Warriors""", """Samfordbulldogs """, """St. Bonaventure Bonnies """,
         """South Carolinagamecocks""", """Simpson Storm""", """South Carolina State Bulldogs""",
         """Santa Clara Broncos""", """Usc Upstate Spartans""", """South Dakota Coyotes""",
         """San Diego Christian Hawks""", """South Dakota State Jackrabbits""", """San Diego State Aztecs""",
         """Seattle Redhawks""", """Southeastern Baptist College Chargers""", """Southeastern Louisianalions""",
         """Southeast Missouri Stateredhawks""", """San Francisco Dons""", """Stephen F. Austinlumberjacks""",
         """St. Francis (Il) Fighting Saints""", """St.Francis (Bkn) Terriers""", """St. Francis (Pa) Red Flash""",
         """San Francisco State Gators""", """Spring Hill Badgers""", """Shenandoah Hornets""", """Shorter Hawks""",
         """Sam Houston Statebearkats""", """Sacred Heart Pioneers""", """Siena Saints""", """Siena Heights Saints""",
         """Simpson University Red Hawks""", """Southern Illinois Salukis""", """Siu-Edwardsville Cougars""",
         """San Jose State Spartans""", """St. John'S Red Storm""", """Saint Katherine Firebirds""",
         """Saint Louis Billikens""", """Saint Mary'S Gaels""", """St. Mary'S College Of Maryland Seahawks""",
         """Smumustangs""", """Sonoma State Seawolves""", """Southern Universityjaguars""",
         """Southern Wesleyan Warriors""", """Spalding Golden Eagles""", """St. Peter'S Peacocks""",
         """St. Andrews Knights""", """Stetson Hatters""", """St. Mary'S (Tx) Rattlers""", """Stony Brook Seawolves""",
         """St. Thomas (Tx) Celts""", """St. Thomas (Fl) Bobcats""", """Southern University At New Orleans Knights""",
         """Suny-Purchase Panthers""", """Suny-Polytechnic Institute Wildcats""", """Southern Utah Thunderbirds""",
         """Southwest Baptist Bearcats""", """Southwestern Christian Eagles""", """Southwestern (Tx) Pirates""",
         """Syracuse Orange""", """Texas A&M International Dustdevils""", """The Apprentice School Builders""",
         """Trinity Baptist Eagles""", """Thomas (Me) Terriers""", """Tcuhorned Frogs""", """Temple Owls""",
         """Tennessee Volunteers""", """Texas Longhorns""", """Toccoa Falls Eagles""", """Thiel Tomcats""",
         """Thomas (Ga) Night Hawks""", """Trinity (Il) Christian College Trolls""", """Tiffin Dragons""",
         """Tulsa Golden Hurricane""", """Texas Lutheran Bulldogs """, """Trevecca Nazarene Trojans""",
         """Tennessee State Tigers""", """Tennessee Tech Golden Eagles""", """Tennessee Wesleyan Bulldogs""",
         """Toledorockets""", """Towson Tigers""", """Trinity (Tx) Tigers""", """Troy Trojans""",
         """Truett-Mcconnell Bears""", """Texas Tech Red Raiders""", """Tulanegreen Wave""", """Texas Wesleyan Rams""",
         """Texas A&Maggies""", """Texas-Dallas Comets""", """Texas Soutern Tigers""", """Texas State Bobcats""",
         """Uab Blazers """, """Arkansas-Fort Smith Lions""", """Arkansas-Little Rock Trojans""",
         """University Of Antelope Valley Pioneers""", """University Of Chicago Maroons""", """Uc Davis Aggies""",
         """Ucf Knights""", """Uc Irvine Anteaters""", """Ucla Bruins""", """Uc Merced Bobcats""",
         """Central Oklahoma Bronchos""", """Uc Riversidehighlanders""", """Uc Santa Barbara Gauchos""",
         """Uc Santa Cruz Banana Slugs""", """Georgia Bulldogs""", """Illinois-Chicago Flames""",
         """Illinois At Springfield Prairie Stars""", """Kentuckty Wildcats""", """Louisiana-Lafayette Ragin' Cajuns""",
         """Louisiana-Monroe Warhawks """, """Mobile Rams """, """Umbc Retrievers""",
         """Maryland-Eastern Shore Hawks""", """Kansas City Roos""", """Missouri-St. Louis Tritons""",
         """Montana-Western Bulldogs""", """North Alabama Lions""", """North Carolinatar Heels""",
         """Unc Asheville Bulldogs """, """Unc Greensboro Spartans """, """Northern Colorado Bears""",
         """North Carolina-Wilmington Seahawks""", """North Dakota Fighting Hawks""", """Nebraska-Kearney Lopers""",
         """North Florida Ospreys""", """New Hampshire Wildcats""", """Northern Iowa Panthers""", """Unlvrebels """,
         """New Mexico Lebos""", """New Orleansprivateers""", """North Texas Mean Green""",
         """University Of Pikeville Bears""", """Puget Sound Loggers""", """Urbana Blue Knights""",
         """Rhode Island Rams""", """South Albama Jaguars""", """Usc Trojans""", """San Diego Toreros""",
         """South Florida Bulls""", """Southern Miss Goldern Eagles""",
         """United States Merchant Marine Academy Mariners""", """Utah State Aggies""", """Texas-Arlington Mavericks""",
         """Utah Utes""", """Tampa Spartans""", """Utep Miners""", """Tennessee-Martin Skyhawks""",
         """Texas Of The Permian Basin Falcons""", """Texas Rio Grande Valley Vaqueros""", """Utsa Roadrunners""",
         """Virginia Cavaliers""", """Virginia-Wise Highland Cavaliers""", """Valley Forge Patriots""",
         """Vermont Catamounts""", """Utah Valley Wolverines""", """Uw-Stout Blue Devils""", """Valparaiso Crusaders""",
         """Vanderbiltcommodores """, """Virginia Commonwealth Rams""", """Villanova Wildcats""",
         """Virginia Military Keydets """, """Virginia Techhokies""", """Vanguard Lions""", """Wagner Seahawks""",
         """Wake Forest Demon Deacons""", """Walla Walla University Wolves""", """Washington Huskies""",
         """Washington Adventist University Shock""", """Wayland Baptist Pioneers""", """Williams Baptist Eagles""",
         """Wiley Wildcats""", """West Coast Baptist Eagles""", """Westcliff University Warriors""",
         """Western Carolina Catamounts""", """Weber State Wildcats""", """Gardner-Webb Runnin' Bulldogs""",
         """Westminster (Ut) Griffins""", """Westmont Warriors""", """Wilberforce Bulldogs""", """Whittier Poets""",
         """Wichita Stateshockers""", """Widene Rpride""", """Wisconsin Lutheran Warriors""", """Winthrop Eagles""",
         """Wisconsinbadgers""", """Western Illinois Leathernecks""", """William Jessup Warriors""",
         """Western Kentucky Hilltoppers""", """Willamette Bearcats""", """William & Mary Tribe""",
         """Westminster (Pa) Titans""", """Western Michigan Broncos""", """Western New Mexico Mustangs""",
         """Wofford Terriers""", """William Peace Pacers""", """Wright State Raiders""",
         """Western Colorado University Mountaineers""", """Washington State Cougars""",
         """West Virginiamountaineers""", """Wyomingcowboys""", """Xavier Musketeers""",
         """Xavier University Of Louisiana Gold Rush""", """Yale Bulldogs""", """Younstown State Penguins"""]
    dictionary = dict(zip(a, b))
    dictionary1 = dict(zip(c, d))
    for i in gopal:
        a=i.contents[1].find("span").text
        b=a.split("/")
        if b[0] in ["10","11","12"]:
            _year= "2019/"
        else:
            _year ="2020/"
        dated= _year+i.contents[1].find("span").text
        dates=dt.datetime.strptime(dated,"%Y/%m/%d").strftime("%Y/%m/%d")
        to_day=dt.datetime.strptime(dated,"%Y/%m/%d").weekday()
        day= calendar.day_name[to_day]
        try:
            if i.contents[7].find_all("span",{"class":"wisbb_status"})[1].text == "TBA":
                timed=tbd
            else:
                timed = i.contents[7].find_all("span", {"class": "wisbb_status"})[1].text
        except:
            timed =tbd
        try:
            if i.contents[7].find("span",{"class":"wisbb_network"}).text == ["none"]:
                networked = tbd
            else:
                networked=i.contents[7].find("span",{"class":"wisbb_network"}).text
        except:
            networked= tbd
        if timed=="TBD":
            times=tbd
        else:
            times= timed[:-3]
        title=i.contents[5].find("label").text
        try:
            list_network=networked.split((","))
            if len(list_network)>0:
                for i in list_network:
                    print(dictionary[team_name]+" at "+dictionary1[c])
                    #print(day + " , " + dates + " , " + times + "," + i + " , " + "NBA_basketbll" + " , " + team_name + " at " + title)
            elif networked == "None":
                print(dictionary[team_name] + " at " + dictionary1[c])
                #print(day + " , " + dates + " , " + times + "," + tbd + " , " + "NBA_basketball" + " , " + team_name+ " at " + title)
        except:
            pass